import './link/app-link.js'
import './title/app-title.js'
import './login/app-login.js'
import './register/app-register.js'
import './notFound/app-not-found.js'
import './root.js'
import './dashboard/app-dashboard.js'
